#server:
#  port: 8081
#  servlet:
#    encoding:
#      charset: utf-8

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/metadb?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: gus200916a^^


  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      '[hibernate.format_sql]': true

  output:
    ansi:
      enabled: always

logging:
  level:
    '[org.springframework.boot.web]': DEBUG
# debug info warn error  